app = 'notehub-api'
primary_region = 'gru'

[build]
  [build.args]
    MMAI = "MMAI"
    MMLK = "MMLK"

[deploy]
  strategy = 'rolling'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  path = "/api/v1/health"
  port = 8080
  timeout = "5s"
  tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024