cors.allowed-origins=http://localhost:3000

spring.servlet.multipart.max-file-size=12MB
spring.data.web.pageable.max-page-size=6660

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${PGHOSTE2E}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSERNAME}
spring.datasource.password=${PGPASSWORD}

geoip.database=${GEOIP_DB}

api.server.host=${SERVER}
api.client.host=${CLIENT}
api.server.security.token.secret=${SECRET}

oauth.github.client.id=${GHCI}
oauth.github.client.secret=${GHCS}

payment.stripe.webhook.key=${SWK}
payment.stripe.publishable.key=${SPK}
payment.stripe.secret.key=${SSK}

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES}
broker.queue.activation.name=default.activation
broker.queue.secret.name=default.secret
broker.queue.password.name=default.password
broker.queue.email.name=default.email
broker.queue.topic.name=default.topic

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.friendly.name=${SPRING_MAIL_FRIENDLY_NAME}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}