cors.allowed-origins=http://localhost:3000
server.port=8080
server.error.include-stacktrace=never

spring.servlet.multipart.max-file-size=12MB
spring.data.web.pageable.max-page-size=6660

spring.flyway.enabled=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:mem:notehub
spring.datasource.username=user
spring.datasource.password=

geoip.database=src/main/resources/geoip/GeoLite2-City.mmdb

api.server.host=http://localhost:8080
api.client.host=http://localhost:3000
api.server.security.token.secret=vasco-da-gama

oauth.github.client.id=ghci
oauth.github.client.secret=ghcs

payment.stripe.webhook.key=swk
payment.stripe.publishable.key=spk
payment.stripe.secret.key=ssk

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:amqp://user:root@localhost:5672}
broker.queue.activation.name=default.activation
broker.queue.secret.name=default.secret
broker.queue.password.name=default.password
broker.queue.email.name=default.email
broker.queue.topic.name=default.topic

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.friendly.name=NoteHub
spring.mail.username=noreply@notehub.com.br
spring.mail.password=

supabase.url=su
supabase.service-role-key=srk