ALTER TABLE users
  ALTER COLUMN avatar TYPE VARCHAR(666),
  ALTER COLUMN banner TYPE VARCHAR(666);

ALTER TABLE users
  ALTER COLUMN avatar DROP NOT NULL;

ALTER TABLE users
  ALTER COLUMN avatar SET DEFAULT NULL,
  ALTER COLUMN banner SET DEFAULT NULL;